version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
    env_file:
      - ../.env

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
